#!/bin/sh
source $1
ENVIRONMENT_SRC=$1
SLIM_PORT=$2
EXECUTABLE_PATH=${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}
APP_PATH=${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app

run_test_system() {
	log "Test System Executable = $EXECUTABLE_PATH"
	log "*** Launching ${PRODUCT_NAME}.app ***"
	$EXECUTABLE_PATH $SLIM_PORT
	log "*** App Exited ***"
	return $?
}

main() {
	log "== RunSlimTestTargetWithSlimPort~OSX:$SLIM_PORT =="
	run_test_system
	exit $?
}

log() {
	echo "[OCSP_RUN]: INFO $1"
}

error() {
	>&2 echo "[OCSP_RUN]: ERROR $1"
	exit 1
}

main
