FITNESSE_SUITE_NAME=$1
REPORT_OUTPUT_FILE_PATH=${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}
${PROJECT_DIR}/LaunchFitnesse -d "${PROJECT_DIR}" -b "$REPORT_OUTPUT_FILE_PATH" --test "$FITNESSE_SUITE_NAME" >&1 
					