#!/bin/sh
MYPATH=$(dirname $0)
source $1
SLIM_PORT=$2
APPLICATION_PATH=${TARGET_BUILD_DIR}/${EXECUTABLE_FOLDER_PATH}
DEPLOYMENT_TARGET_VALUE=$( echo "$DEPLOYMENT_TARGET_SUGGESTED_VALUES" | rev | cut -d " " -f1 | rev )

get_app_executable_name() {
	echo $(defaults read $APPLICATION_PATH/Info CFBundleExecutable)
	#echo $(/usr/libexec/PlistBuddy -c "Print :CFBundleExecutable" "$APPLICATION_PATH/Info.plist")
}

get_app_devicetypeid() {

	local DEVICETYPE_ID=
	local BOOTED_DEVICE_NAME=$(xcrun simctl list devices | grep "Booted" | cut -d "(" -f1 | awk '{gsub(/^ +| +$/,"")} {print $0}')
	
	if [ ! -z "$BOOTED_DEVICE_NAME" ]; then
		DEVICETYPE_ID=$(xcrun simctl list devicetypes | grep "^$BOOTED_DEVICE_NAME (com.apple" | cut -d "(" -f2 | cut -d ")" -f1)
	else
		DEVICETYPE_ID=$(xcrun simctl list devicetypes | grep "$DEVICE_TYPE" | tail -n1 | cut -d "(" -f2 | cut -d ")" -f1)
	fi
	
	if [ -z "$DEVICETYPE_ID" ]; then
		echo "Device Type Identifier For $DEVICE_TYPE Missing"
		exit 1
	fi

	echo "$DEVICETYPE_ID, $DEPLOYMENT_TARGET_VALUE"
}

slim_system_wait() {
	
	local EXECUTABLE_PID=
	local EXECUTABLE_NAME=$(get_app_executable_name)
	
	echo "[OCSP_RUN] Waiting for Slim Test System To Launch"
	while [ -z "$EXECUTABLE_PID" ] 
	do
		EXECUTABLE_PID=$(pgrep "$EXECUTABLE_NAME")
	done
	
	echo "[OCSP_RUN] Slim System Detected ($EXECUTABLE_PID)"
	while [[ "$EXECUTABLE_PID" ]]
	do
		EXECUTABLE_PID=$(pgrep "$EXECUTABLE_NAME")
		sleep 0.5
	done
}

run_test_system() {
	echo "[OCSP_RUN] == Start Slim Test Sytem (Simulator System $(xcrun simctl --version) =="
	$MYPATH/ocsp-simctl $APPLICATION_PATH $SLIM_PORT
 	if [ $? == 0 ]; then slim_system_wait; else return 1; fi
}

main() {
	echo "[OCSP_RUN] == RunSlimTestTargetWithSlimPort~iOS:$SLIM_PORT $(date)=="
	echo "[OCSP_RUN] Info: Test System Suggested SDK: $DEPLOYMENT_TARGET_VALUE"
	echo "[OCSP_RUN] Info: Test System Path: $APPLICATION_PATH"
	run_test_system
	exit $?
}

main
